// Figma: https://www.figma.com/design/4rJmEFUU2HMWVy3qUcYZRs/%EC%A0%9C%EB%AA%A9-%EC%97%86%EC%9D%8C?node-id=1-5893
// Figma-states: qnaList

import type { QnaQuestion } from './types';

export const MOCK_QNA_QUESTIONS: QnaQuestion[] = [
  {
    id: 10501,
    category: { id: 12, depth: 2, names: ["백엔드", "Django", "ORM"] },
    author: { id: 211, nickname: "한율_회장", profile_image_url: null },
    title: "Django ORM 역참조는 어떻게 사용하나요?",
    content_preview: "ForeignKey에 related_name을 지정하면 역참조가 가능하다고 들었는데, 실제 사용법이 궁금합니다.",
    answer_count: 3,
    view_count: 87,
    created_at: "2025-03-01 10:03:21",
    thumbnail_img_url: null,
  },
  {
    id: 10502,
    category: { id: 15, depth: 2, names: ["프론트엔드", "React", "Hooks"] },
    author: { id: 212, nickname: "김멘토", profile_image_url: null },
    title: "오류가 발생했다고 뜨네요.",
    content_preview: "터미널에서 실행했을 때 에러가 발생합니다. node.js에서 찾아낸 것을 할 수 있는지 궁금합니다.",
    answer_count: 2,
    view_count: 45,
    created_at: "2025-03-02 14:22:10",
    thumbnail_img_url: null,
  },
  {
    id: 10503,
    category: { id: 18, depth: 2, names: ["프론트엔드", "JavaScript", "기초"] },
    author: { id: 213, nickname: "이수강", profile_image_url: null },
    title: "new 함수를 써야 하는 실행 예시에 대해서",
    content_preview: "함수 안 void를 사용할 때 어떤 의미인지, 모든 경우에 사용할 수 있는지 궁금합니다.",
    answer_count: 1,
    view_count: 32,
    created_at: "2025-03-03 09:15:44",
    thumbnail_img_url: null,
  },
  {
    id: 10504,
    category: { id: 12, depth: 2, names: ["백엔드", "Django", "Views"] },
    author: { id: 214, nickname: "박개발", profile_image_url: null },
    title: "Django REST Framework serializer 질문입니다",
    content_preview: "ModelSerializer에서 커스텀 필드를 추가하는 방법이 궁금합니다. 공식 문서를 봐도 이해가 안 됩니다.",
    answer_count: 0,
    view_count: 12,
    created_at: "2025-03-04 16:30:00",
    thumbnail_img_url: null,
  },
  {
    id: 10505,
    category: { id: 20, depth: 2, names: ["기타", "Git", "브랜치"] },
    author: { id: 215, nickname: "최코딩", profile_image_url: null },
    title: "Git merge conflict 해결 방법이 궁금합니다",
    content_preview: "팀 프로젝트에서 같은 파일을 수정했을 때 conflict가 발생하는데, 어떻게 해결하나요?",
    answer_count: 0,
    view_count: 28,
    created_at: "2025-03-05 11:00:00",
    thumbnail_img_url: null,
  },
  {
    id: 10506,
    category: { id: 15, depth: 2, names: ["프론트엔드", "React", "상태관리"] },
    author: { id: 216, nickname: "정리액트", profile_image_url: null },
    title: "useEffect 무한 루프 문제",
    content_preview: "useEffect 안에서 setState를 호출하면 무한 루프가 발생합니다. 의존성 배열을 어떻게 설정해야 하나요?",
    answer_count: 5,
    view_count: 120,
    created_at: "2025-03-06 08:45:00",
    thumbnail_img_url: null,
  },
  {
    id: 10507,
    category: { id: 18, depth: 2, names: ["프론트엔드", "TypeScript", "타입"] },
    author: { id: 217, nickname: "강타입", profile_image_url: null },
    title: "TypeScript 제네릭 사용법",
    content_preview: "제네릭을 사용하면 재사용성이 높아진다고 하는데, 실제 프로젝트에서 어떻게 활용하나요?",
    answer_count: 2,
    view_count: 65,
    created_at: "2025-03-07 13:20:00",
    thumbnail_img_url: null,
  },
  {
    id: 10508,
    category: { id: 12, depth: 2, names: ["백엔드", "Python", "기초"] },
    author: { id: 218, nickname: "윤파이썬", profile_image_url: null },
    title: "Python 가상환경 설정 오류",
    content_preview: "venv를 생성하고 activate했는데 패키지 설치가 시스템에 설치됩니다. 어떻게 해결하나요?",
    answer_count: 1,
    view_count: 40,
    created_at: "2025-03-08 15:10:00",
    thumbnail_img_url: null,
  },
];
