// Figma: https://www.figma.com/design/4rJmEFUU2HMWVy3qUcYZRs/%EC%A0%9C%EB%AA%A9-%EC%97%86%EC%9D%8C?node-id=1-9801
// Figma-states: communityList

import type { CommunityPost } from './types';

export const MOCK_POSTS: CommunityPost[] = [
  {
    id: 1,
    category: "구인/채용",
    title: "데이터 분석 프로젝트 구합니다",
    content: "HR 관련 프로젝트를 하고 싶은 프로젝트를 하는 분이 있으면 편하게 연락주세요~",
    author: "홍길동",
    date: "14시간 전",
    commentCount: 7,
    viewCount: 180,
    likeCount: 0,
  },
  {
    id: 2,
    category: "자유게시판",
    title: "러닝 페이스 잡혀요.",
    content: "하루에 5km씩 꾸준히 달리고 있는데, 드디어 러닝 페이스가 잡히기 시작했어요.",
    author: "김멘토",
    date: "14시간 전",
    commentCount: 2,
    viewCount: 35,
    likeCount: 0,
  },
  {
    id: 3,
    category: "자유게시판",
    title: "월요일 파이팅..",
    content: "",
    author: "HG",
    date: "14시간 전",
    commentCount: 2,
    viewCount: 35,
    likeCount: 0,
  },
  {
    id: 4,
    category: "고민",
    title: "프론트엔드 개발자 취업 고민",
    content: "부트캠프 수료 후 취업 준비 중인데 포트폴리오 어떻게 준비하셨나요?",
    author: "취준생A",
    date: "1일 전",
    commentCount: 12,
    viewCount: 340,
    likeCount: 5,
  },
  {
    id: 5,
    category: "공지사항",
    title: "2026년 3월 커뮤니티 운영 안내",
    content: "커뮤니티 이용 규칙이 업데이트 되었습니다. 확인 부탁드립니다.",
    author: "관리자",
    date: "2일 전",
    commentCount: 0,
    viewCount: 520,
    likeCount: 3,
  },
  {
    id: 6,
    category: "자유게시판",
    title: "오늘 코딩 테스트 후기",
    content: "카카오 코딩테스트 봤는데 생각보다 어려웠어요. 다들 어떠셨나요?",
    author: "코더",
    date: "2일 전",
    commentCount: 8,
    viewCount: 210,
    likeCount: 2,
  },
  {
    id: 7,
    category: "구인/채용",
    title: "React 프로젝트 팀원 모집합니다",
    content: "사이드 프로젝트로 일정 관리 앱을 만들 예정입니다. 프론트 2명 모집합니다.",
    author: "PM김",
    date: "3일 전",
    commentCount: 15,
    viewCount: 430,
    likeCount: 7,
  },
  {
    id: 8,
    category: "고민",
    title: "백엔드 vs 프론트엔드 진로 고민",
    content: "두 분야 모두 재미있는데 어떤 걸 메인으로 잡아야 할지 모르겠어요.",
    author: "고민맨",
    date: "3일 전",
    commentCount: 20,
    viewCount: 580,
    likeCount: 10,
  },
  {
    id: 9,
    category: "자유게시판",
    title: "추천 개발 유튜브 채널",
    content: "최근에 발견한 좋은 개발 유튜브 채널 공유합니다.",
    author: "유튜버팬",
    date: "4일 전",
    commentCount: 6,
    viewCount: 150,
    likeCount: 4,
  },
  {
    id: 10,
    category: "인기글",
    title: "신입 개발자 연봉 현실",
    content: "실제 신입 개발자 연봉 범위에 대해 이야기 나눠봐요.",
    author: "현실주의",
    date: "4일 전",
    commentCount: 45,
    viewCount: 1200,
    likeCount: 30,
  },
  {
    id: 11,
    category: "자료 >",
    title: "TypeScript 핸드북 정리",
    content: "타입스크립트 공식 문서를 한글로 정리했습니다. 필요하신 분 참고하세요.",
    author: "정리왕",
    date: "5일 전",
    commentCount: 3,
    viewCount: 280,
    likeCount: 12,
  },
  {
    id: 12,
    category: "구인/채용",
    title: "스타트업 프론트엔드 개발자 채용",
    content: "시리즈A 스타트업에서 주니어 프론트엔드 개발자를 찾고 있습니다.",
    author: "스타트업HR",
    date: "5일 전",
    commentCount: 4,
    viewCount: 310,
    likeCount: 1,
  },
  {
    id: 13,
    category: "자유게시판",
    title: "개발자 번아웃 극복기",
    content: "번아웃 왔을 때 어떻게 극복하셨나요? 저만의 방법을 공유합니다.",
    author: "회복중",
    date: "6일 전",
    commentCount: 11,
    viewCount: 390,
    likeCount: 8,
  },
  {
    id: 14,
    category: "고민",
    title: "코딩 부트캠프 vs 독학",
    content: "비전공자인데 부트캠프를 다닐지 독학할지 고민입니다.",
    author: "비전공자",
    date: "1주 전",
    commentCount: 18,
    viewCount: 620,
    likeCount: 6,
  },
  {
    id: 15,
    category: "공지사항",
    title: "서비스 점검 안내 (3/25)",
    content: "3월 25일 오전 2시~6시 서비스 점검이 예정되어 있습니다.",
    author: "관리자",
    date: "1주 전",
    commentCount: 1,
    viewCount: 440,
    likeCount: 0,
  },
];
